/* JLG Project Lab 360 — V10 Final: AI Studio, autosync and delivery QA */
function ensureV10AiState(){ensureV10State();state.final.ai=state.final.ai||{};state.final.ai.endpoint=state.final.ai.endpoint||localStorage.getItem('jlg360_ai_endpoint')||'';state.final.ai.mode=state.final.ai.mode||'analysis';state.final.ai.history=Array.isArray(state.final.ai.history)?state.final.ai.history:[]}
function aiProjectDigestV10(){const f=calcFinance(),s=scoreProject();return{name:state.name,mode:state.mode,type:state.type,site:state.site,ownership:state.ownership,location:state.location,target:state.target,goal:state.goal,idea:state.idea,decision:s.verdict,confidence:s.confidence,finance:{revenue:f.revenue,profit:f.profit,capex:f.capex,breakeven:f.breakeven},risks:risks().slice(0,8),territory:state.territory?.live?{nom:state.territory.live.nom,code:state.territory.live.code,population:state.territory.live.population}:null,premium:{riskCount:state.premium?.risks?.list?.length||0,urbanZones:state.premium?.urbanism?.zones?.slice(0,4)||[]},roadmap:typeof roadmapItems==='function'?roadmapItems().slice(0,20):[],documents:typeof allDocuments==='function'?allDocuments().slice(0,30):[]}}
function aiMissionV10(mode=state.final.ai.mode){let base='';try{base=buildBrief()}catch{base=`Projet: ${state.name||'Sans nom'}\nIdée: ${state.idea||'À compléter'}`}
  if(mode==='visual'){const zones=typeof variantSurfaces==='function'?variantSurfaces():[];return `${base}\n\n## MISSION VISUELLE V10\nProduire un concept visuel professionnel cohérent avec les données connues. Type: ${labels[state.type]||state.type}. Site: ${siteLabels[state.site]||state.site}. Variante: ${typeof V5_VARIANTS!=='undefined'&&state.visual?.variant?V5_VARIANTS[state.visual.variant]?.label||state.visual.variant:'standard'}. Programme: ${zones.map(x=>x[0]+' '+x[1]+'%').join(' ; ')}.\nNe pas inventer dimensions, autorisations ou éléments physiques non fournis. Rendre explicites les hypothèses. Pour un rendu, privilégier lisibilité du parcours, sécurité, flux public/service et intégration réaliste au site.`}
  if(mode==='pitch'){return `${base}\n\n## MISSION PITCH V10\nCréer un pitch de 60 secondes, structuré en 7 séquences : problème/opportunité, concept, territoire, modèle économique, avantage, risque maîtrisé, prochaine décision. Ton professionnel, concret, sans promesse non prouvée. Fournir aussi un storyboard de 8 plans.`}
  return `${base}\n\n## MISSION ANALYSE V10\nAgir comme un bureau d'études senior. Challenger les hypothèses, distinguer faits / estimations / inconnues, prioriser les blocages, proposer des validations terrain et produire une recommandation GO / GO sous conditions / PIVOT / NO-GO. Toute donnée réglementaire ou territoriale doit être sourcée et datée.`}
}
function setAiModeV10(mode){ensureV10AiState();state.final.ai.mode=mode;$$('[data-v10-ai-mode]').forEach(b=>b.classList.toggle('active',b.dataset.v10AiMode===mode));const p=$('#v10AiPrompt');if(p)p.value=aiMissionV10(mode);save(false)}
function renderAiV10(){ensureV10AiState();const ep=$('#v10AiEndpoint');if(ep)ep.value=state.final.ai.endpoint||'';$$('[data-v10-ai-mode]').forEach(b=>b.classList.toggle('active',b.dataset.v10AiMode===state.final.ai.mode));const health=$('#aiGatewayHealth');if(health){health.className='status '+(state.final.ai.endpoint?'ok':'alert');health.textContent=state.final.ai.endpoint?'PRÊTE':'OPTIONNEL'}const result=$('#v10AiResult');if(result&&state.final.ai.history.length){const h=state.final.ai.history[0];result.innerHTML=`<div class="ai-result-head"><b>${esc(h.mode.toUpperCase())}</b><span class="pill">${new Date(h.date).toLocaleString('fr-FR')}</span></div>${h.imageUrl?`<img src="${esc(h.imageUrl)}" alt="Résultat visuel IA" class="ai-output-img">`:''}${h.text?`<div class="ai-output-text">${esc(h.text).replace(/\n/g,'<br>')}</div>`:''}`}}
function saveAiEndpointV10(){ensureV10AiState();state.final.ai.endpoint=($('#v10AiEndpoint')?.value||'').trim().replace(/\/$/,'');localStorage.setItem('jlg360_ai_endpoint',state.final.ai.endpoint);save(false);renderAiV10()}
async function sendAiV10(){ensureV10AiState();saveAiEndpointV10();const endpoint=state.final.ai.endpoint,prompt=($('#v10AiPrompt')?.value||aiMissionV10()).trim();if(!endpoint)return toast('Configure une passerelle IA sécurisée.');if(!prompt)return toast('Construis une mission.');const box=$('#v10AiResult');if(box)box.innerHTML='<p><b>Génération en cours…</b></p>';try{const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode:state.final.ai.mode,prompt,project:aiProjectDigestV10()})});if(!r.ok)throw new Error('Passerelle IA HTTP '+r.status);const j=await r.json();const text=String(j.text||j.output||j.message||''),imageUrl=j.image_url||j.imageUrl||j.url||'';if(!text&&!imageUrl)throw new Error('Réponse IA vide.');state.final.ai.history.unshift({mode:state.final.ai.mode,date:new Date().toISOString(),text,imageUrl});state.final.ai.history=state.final.ai.history.slice(0,12);save(false);renderAiV10();toast('Résultat IA reçu')}catch(e){if(box)box.innerHTML=`<div class="callout bad"><b>Échec de la passerelle.</b> ${esc(e.message)}</div>`;toast(e.message)}}
function downloadAiBriefV10(){const prompt=($('#v10AiPrompt')?.value||aiMissionV10()).trim(),content=`JLG Project Lab 360 — V10\nMode: ${state.final.ai.mode}\nProjet: ${state.name||'Sans nom'}\n\n${prompt}`;downloadBlobV9((slug(state.name)||'projet')+'-brief-ia-v10.txt',content,'text/plain;charset=utf-8');toast('Brief IA téléchargé')}
function bindAiV10(){$$('[data-v10-ai-mode]').forEach(b=>b.onclick=()=>setAiModeV10(b.dataset.v10AiMode));$('#v10BuildAi')&&($('#v10BuildAi').onclick=()=>{const p=$('#v10AiPrompt');if(p)p.value=aiMissionV10();toast('Mission construite')});$('#v10SendAi')&&($('#v10SendAi').onclick=sendAiV10);$('#v10DownloadAi')&&($('#v10DownloadAi').onclick=downloadAiBriefV10);$('#v10AiEndpoint')&&($('#v10AiEndpoint').onchange=saveAiEndpointV10)}
let autoSyncTimerV10=null;function scheduleAutoSyncV10(){ensureV10State();if(!state.final.sync.auto||!state.final.sync.endpoint||state.final.sync.channelCode.replace(/-/g,'').length<16)return;clearTimeout(autoSyncTimerV10);autoSyncTimerV10=setTimeout(()=>pushSyncV10({silent:true}),1800)}
function wrapSaveForV10(){if(window.__v10SaveWrapped)return;window.__v10SaveWrapped=true;const old=save;save=function(notify=true){const out=old(notify);if(notify)scheduleAutoSyncV10();return out}}
async function qaCryptoRoundtripV10(){const code='ABCD-EFGH-JKLM-NPQR-STUV',sample={hello:'world',n:42};const e=await encryptProjectV10(sample,code),d=await decryptProjectV10(e,code);return d.hello==='world'&&d.n===42}
async function runFinalQaV10(){ensureV10AiState();const checks=[],test=async(n,fn)=>{try{checks.push([n,!!(await fn()),''])}catch(e){checks.push([n,false,e.message])}};
  await test('Version V10 chargée',()=>V10_VERSION==='10.0.0');await test('État projet sérialisable',()=>!!JSON.parse(JSON.stringify(state)));await test('Chiffrement AES-GCM aller-retour',qaCryptoRoundtripV10);await test('Code sync à forte entropie',()=>generateSyncCode().replace(/-/g,'').length===20);await test('Plan interactif conservé',()=>typeof renderVisualsV5==='function'&&typeof variantSurfaces==='function');await test('Workflow 30/60/90 conservé',()=>typeof roadmapItems==='function'&&roadmapItems().length>5);await test('Documents conservés',()=>typeof allDocuments==='function'&&allDocuments().length>=10);await test('Montage V7 conservé',()=>typeof executionScore==='function'&&typeof permitTemplates==='function');await test('Territoire live conservé',()=>typeof researchTerritory==='function');await test('Premium Géorisques/urbanisme conservé',()=>typeof runPremiumResearch==='function'&&typeof premiumCompletion==='function');await test('Livrables SVG conservés',()=>typeof decisionSvg==='function'&&typeof riskMatrixSvg==='function');await test('Pack exécutif conservé',()=>typeof executivePackHtml==='function');await test('Import/export projet',()=>typeof exportJson==='function'&&typeof importJson==='function');await test('Studio IA construit une mission',()=>aiMissionV10('analysis').length>200);await test('Mode hors ligne PWA disponible',()=>('serviceWorker'in navigator));await test('Aucun ID dupliqué dans le DOM',()=>{const ids=$$('[id]').map(x=>x.id);return ids.length===new Set(ids).size});await test('Toutes les pages de navigation existent',()=>$$('.tab[data-page]').every(b=>!!document.getElementById(b.dataset.page)));
  const ok=checks.filter(x=>x[1]).length,el=$('#v10FinalQa');if(el)el.innerHTML=`<div class="final-qa-score ${ok===checks.length?'pass':'warn'}"><strong>${ok}/${checks.length}</strong><span>contrôles réussis</span></div>`+checks.map(([n,v,e])=>`<div class="qa-item"><header><b>${esc(n)}</b><span class="status ${v?'ok':'block'}">${v?'OK':'ÉCHEC'}</span></header>${e?`<p>${esc(e)}</p>`:''}</div>`).join('');toast(`${ok}/${checks.length} contrôles V10 réussis`);return{ok,total:checks.length,checks}}
function bindFinalV10(){const newTab=$('.tab[data-page="syncfinal"]');if(newTab)newTab.onclick=()=>showPage('syncfinal');$('#v10RunQa')&&($('#v10RunQa').onclick=runFinalQaV10);$('#v10Backup')&&($('#v10Backup').onclick=exportJson);bindSyncV10();bindAiV10()}
const V10_oldShowPage=showPage;showPage=function(id){V10_oldShowPage(id);if(id==='syncfinal'){renderSyncV10();renderAiV10()}};
const V10_oldRenderAll=renderAll;renderAll=function(){ensureV10State();ensureV10AiState();V10_oldRenderAll();renderSyncV10();renderAiV10()};
function initV10(){ensureV10State();restoreQueueV10();ensureV10AiState();injectV10Shell();wrapSaveForV10();bindFinalV10();renderSyncV10();renderAiV10();if(!$('#v10AiPrompt')?.value)$('#v10AiPrompt').value=aiMissionV10();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js?v=10.0.0').then(r=>r.update()).catch(()=>{});setTimeout(()=>runFinalQaV10(),350)}
initV10();
