const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], clamp=(n,a=0,b=100)=>Math.max(a,Math.min(b,n)), fmt=n=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(Number(n||0)), num=id=>Number($('#'+id)?.value||0), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={personal:'Personnel',business:'Entrepreneurial',organization:'Organisation',public:'Public / territoire',commerce:'Commerce',food:'Restauration / bar',event:'Événementiel',tourism:'Tourisme / loisirs',realestate:'Immobilier / aménagement',digital:'Application / digital',services:'Services',sport:'Sport',association:'Association',free:'Projet libre'};
const siteLabels={unknown:'À définir',hotel:'Hôtel',camping:'Camping',shop:'Local commercial',square:'Place publique',river:'Bord de rivière',lake:'Bord de lac',castle:'Château / patrimoine',land:'Terrain',private:'Site privé',publicsite:'Site public',home:'Domicile',digital:'Site digital',other:'Autre'};
let state={id:null,name:'',mode:'business',type:'food',site:'unknown',ownership:'unknown',location:'',budget:0,deadline:'',target:'',goal:'',idea:'',answers:{},evidence:[],analysis:null,finance:{},pitchIndex:0};
const toast=t=>{const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)};
function readProject(){['name','mode','type','site','ownership','location','deadline','target','goal','idea'].forEach(k=>state[k]=$('#'+k).value);state.budget=num('budget');}
function fillProject(){['name','mode','type','site','ownership','location','deadline','target','goal','idea'].forEach(k=>$('#'+k).value=state[k]??'');$('#budget').value=state.budget||'';}
function financeInputs(){const ids=['avgPrice','qty','margin','extraRevenue','variableExtra','activeMonths','rent','staff','marketing','utilities','debt','otherOpex','capexWorks','capexEquip','capexOther','equity','loan','grants'];ids.forEach(k=>state.finance[k]=num(k));}
function fillFinance(){const d={avgPrice:18,qty:800,margin:68,extraRevenue:0,variableExtra:0,activeMonths:12,rent:0,staff:0,marketing:0,utilities:0,debt:0,otherOpex:0,capexWorks:0,capexEquip:0,capexOther:0,equity:0,loan:0,grants:0};Object.entries(d).forEach(([k,v])=>$('#'+k).value=state.finance?.[k]??v)}
