function territoryMetrics(){const c=state.territory.live,p=state.territory.poi||[];if(!c)return{};const comp=p.filter(x=>x.category==='competition').length,tour=p.filter(x=>x.category==='tourism').length,access=p.filter(x=>x.category==='access').length,services=p.filter(x=>x.category==='services').length,density=c.surface?c.population/(c.surface/100):null;return{comp,tour,access,services,density}}
function territoryReading(){const c=state.territory.live,m=territoryMetrics(),out=[];if(!c)return['Aucune donnée live chargée.'];
  if(c.population<3000)out.push('Commune de petite taille : ne pas baser le modèle uniquement sur la clientèle résidente ; raisonner bassin de vie, tourisme et flux.');else if(c.population<15000)out.push('Marché local intermédiaire : la répétition d’achat et la zone de chalandise deviennent déterminantes.');else out.push('Base de population locale significative : le projet peut tester plusieurs segments, mais la concurrence doit être qualifiée.');
  if(m.comp>=12)out.push(`Offre/concurrence repérée assez dense (${m.comp} éléments dans le rayon) : la différenciation doit être explicite.`);else out.push(`Peu d’offres comparables repérées automatiquement (${m.comp}) : opportunité possible, mais vérifier qu’il ne s’agit pas d’un manque de données OSM.`);
  if(m.tour>=8)out.push(`Présence touristique visible (${m.tour} points repérés) : intégrer saisonnalité, partenariats et captation des visiteurs.`);
  if(m.access===0)out.push('Aucun parking/station repéré automatiquement : l’accès doit être vérifié manuellement avant de conclure.');
  if(['lake','river','castle','tourism'].includes(state.site)||state.type==='tourism')out.push('Le lieu lui-même peut être un moteur d’attractivité ; mesurer les flux réels plutôt que supposer leur conversion en clients.');
  return out;
}
function territoryImpact(){const out=[],c=state.territory.live,m=territoryMetrics();if(!c)return out;
  out.push({level:'good',title:'Donnée territoire validée',text:`Commune identifiée officiellement : ${c.nom} (${c.code}).`});
  if(m.comp>15)out.push({level:'warn',title:'Pression concurrentielle à qualifier',text:`${m.comp} offres/activités comparables ou proches repérées automatiquement.`});
  if(m.tour>5)out.push({level:'good',title:'Levier touristique potentiel',text:`${m.tour} points touristiques/hébergements repérés dans le rayon.`});
  if((state.finance?.qty||0)>c.population*.5&&c.population<10000)out.push({level:'bad',title:'Volume à challenger',text:'Le volume mensuel saisi est élevé par rapport à la population communale ; prouver l’apport du bassin de vie, tourisme ou passage.'});
  if(!state.evidence.some(e=>/march|client|vente|sondage|fréquent/i.test(e.label+' '+e.detail)))out.push({level:'warn',title:'Toujours pas une étude de marché',text:'Les données territoriales donnent le contexte, mais ne prouvent pas que des clients achèteront l’offre.'});
  return out;
}
let poiFilterV8='all';
function renderTerritory(){
  ensureV8State();const c=state.territory.live,k=$('#territoryKpis'),profile=$('#communeProfile'),reading=$('#territoryReading'),status=$('#territoryStatus'),sources=$('#territorySources'),impact=$('#territoryImpact'),list=$('#poiList'),count=$('#poiCount');if(!k)return;
  $('#territoryRadius')&&($('#territoryRadius').value=String(state.territory.radius||5000));$('#territoryTitle')&&($('#territoryTitle').textContent=c?.nom||state.location||'Ville à définir');
  if(!c){k.innerHTML='';profile.innerHTML='<p class="muted">Aucune donnée officielle chargée.</p>';reading.innerHTML='<p class="muted">Lance une analyse du territoire.</p>';list.innerHTML='<p class="muted">Aucun point d’intérêt chargé.</p>';sources.innerHTML='<p class="muted">Aucune source enregistrée.</p>';impact.innerHTML='';if(status)status.textContent='Aucune donnée live chargée.';return}
  const m=territoryMetrics(),km2=c.surface?c.surface/100:null;
  k.innerHTML=[['Population',frNumber(c.population)],['Surface',km2?frNumber(Math.round(km2))+' km²':'—'],['Offre repérée',m.comp],['Tourisme repéré',m.tour]].map(([n,v])=>`<div class="kpi"><span>${esc(n)}</span><strong>${esc(v)}</strong></div>`).join('');
  profile.innerHTML=`<div class="official-profile"><div><span>Commune</span><b>${esc(c.nom)}</b></div><div><span>Code INSEE</span><b>${esc(c.code)}</b></div><div><span>Codes postaux</span><b>${esc((c.codesPostaux||[]).join(', ')||'—')}</b></div><div><span>Département</span><b>${esc(c.departement?.nom||'—')}</b></div><div><span>Région</span><b>${esc(c.region?.nom||'—')}</b></div><div><span>EPCI</span><b>${esc(c.epci?.nom||'—')}</b></div>${m.density?`<div><span>Densité indicative</span><b>${frNumber(Math.round(m.density))} hab./km²</b></div>`:''}</div>`;
  reading.innerHTML=`<ul class="list">${territoryReading().map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`;
  const all=state.territory.poi||[],filtered=poiFilterV8==='all'?all:all.filter(x=>x.category===poiFilterV8);if(count)count.textContent=`${all.length} éléments`;
  list.innerHTML=filtered.length?filtered.slice(0,60).map(x=>`<div class="poi-row"><div><b>${esc(x.name)}</b><small>${esc(x.category==='competition'?'Offre / concurrence':x.category==='access'?'Accès / mobilité':x.category==='tourism'?'Tourisme / hébergement':'Service')}</small></div><span class="pill">${x.distance.toFixed(1)} km</span></div>`).join(''):'<p class="muted">Aucun élément dans ce filtre.</p>';
  $$('[data-poi-filter]').forEach(b=>{b.classList.toggle('active',b.dataset.poiFilter===poiFilterV8);b.onclick=()=>{poiFilterV8=b.dataset.poiFilter;renderTerritory()}});
  sources.innerHTML=(state.territory.sources||[]).map(s=>`<div class="source-row"><div><b>${esc(s.label)}</b><small>${esc(s.date)}</small></div><span class="status ok">LIVE</span></div>`).join('')+(state.territory.poiError?`<div class="callout warn" style="margin-top:10px">Écosystème local incomplet : ${esc(state.territory.poiError)}</div>`:'');
  impact.innerHTML=territoryImpact().map(x=>`<div class="impact-row ${x.level}"><b>${esc(x.title)}</b><p>${esc(x.text)}</p></div>`).join('')||'<p class="muted">Aucun impact particulier détecté.</p>';
  if(status)status.innerHTML=`<b>Données actualisées le ${new Date(state.territory.updatedAt).toLocaleString('fr-FR')}.</b> Rayon OSM : ${Math.round(state.territory.radius/1000)} km. Les résultats OpenStreetMap sont indicatifs et doivent être vérifiés.`;
}
function clearTerritory(){ensureV8State();state.territory={live:null,poi:[],sources:[],radius:Number($('#territoryRadius')?.value||5000),updatedAt:null};save(false);renderTerritory();toast('Données territoriales effacées')}
function addV8Dossier(){const d=$('#dossierContent');if(!d||!state.analysis||!state.territory?.live||d.querySelector('.v8-territory-dossier'))return;const c=state.territory.live,m=territoryMetrics();d.insertAdjacentHTML('beforeend',`<div class="v8-territory-dossier"><h2>Territoire & données live V8</h2><p><b>${esc(c.nom)}</b> · ${frNumber(c.population)} habitants · ${c.departement?.nom?esc(c.departement.nom):''} · données récupérées le ${new Date(state.territory.updatedAt).toLocaleDateString('fr-FR')}.</p><table><thead><tr><th>Indicateur</th><th>Valeur</th><th>Lecture</th></tr></thead><tbody><tr><td>Population communale</td><td>${frNumber(c.population)}</td><td>Contexte, pas preuve de demande.</td></tr><tr><td>Offres/activités repérées</td><td>${m.comp}</td><td>Repérage OpenStreetMap dans ${Math.round(state.territory.radius/1000)} km.</td></tr><tr><td>Tourisme/hébergements repérés</td><td>${m.tour}</td><td>Indicateur de contexte touristique.</td></tr><tr><td>Accès repérés</td><td>${m.access}</td><td>Parkings/stations uniquement si renseignés dans OSM.</td></tr></tbody></table><h3>Lecture stratégique</h3><ul>${territoryReading().map(x=>`<li>${esc(x)}</li>`).join('')}</ul><p class="footer-note">Sources : geo.api.gouv.fr et © OpenStreetMap contributors / Overpass. Ces données contextuelles doivent être complétées par étude terrain, vérification réglementaire et données commerciales réelles.</p></div>`)}
const V8_oldShowPage=showPage;showPage=function(id){V8_oldShowPage(id);if(id==='territory')renderTerritory()};
const V8_oldRenderAll=renderAll;renderAll=function(){ensureV8State();V8_oldRenderAll();renderTerritory();addV8Dossier()};
const V8_oldRenderDossier=renderDossier;renderDossier=function(){V8_oldRenderDossier();addV8Dossier()};
function bindV8(){
  $$('.tab').forEach(b=>{if(!b.dataset.v8bound){b.dataset.v8bound='1';b.addEventListener('click',()=>{if(b.dataset.page==='territory')setTimeout(renderTerritory,0)})}});
  $('#researchTerritoryBtn')&&($('#researchTerritoryBtn').onclick=researchTerritory);$('#clearTerritoryBtn')&&($('#clearTerritoryBtn').onclick=clearTerritory);$('#territoryRadius')&&($('#territoryRadius').onchange=e=>{state.territory.radius=Number(e.target.value);save(false)});
}
function extendAutoTestsV8(){const old=window.autoTestsV5;if(!old)return;window.autoTestsV5=function(){old();setTimeout(()=>{const checks=[['V8 territoire live',!!$('#territory')],['API commune configurée',fetchCommuneLive instanceof Function],['Cache territoire',typeof territoryCacheKey()==='string'],['Lecture territoriale',Array.isArray(territoryReading())],['Traçabilité sources',Array.isArray(state.territory.sources)]];$('#testResults')?.insertAdjacentHTML('beforeend',checks.map(([n,ok])=>`<div class="qa-item"><header><b>${esc(n)}</b><span class="status ${ok?'ok':'block'}">${ok?'OK':'ÉCHEC'}</span></header></div>`).join(''))},160)};$('#autoTestBtn')&&($('#autoTestBtn').onclick=window.autoTestsV5)}
function initV8(){ensureV8State();injectV8Shell();bindV8();extendAutoTestsV8();renderAll();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js?v=8.0.0').then(r=>r.update()).catch(()=>{});}
initV8();
