/* JLG Project Lab 360 — V8 real deliverables */
function injectV8Deliverables(){
  const tabs=$('#tabs');if(tabs&&!tabs.querySelector('[data-page="deliverables"]')){const dossier=tabs.querySelector('[data-page="dossier"]');dossier?.insertAdjacentHTML('beforebegin','<button class="tab" data-page="deliverables">Livrables</button>')}
  const dossier=$('#dossier');if(dossier&&!$('#deliverables'))dossier.insertAdjacentHTML('beforebegin',`<section id="deliverables" class="page">
    <div class="section-title"><div><span class="section-kicker">V8 · PRODUCTION</span><h2>Livrables exploitables</h2></div><p>Générés à partir des données du projet, sans inventer ce qui manque.</p></div>
    <div id="deliverableSummary" class="grid g4"></div>
    <div class="deliverable-grid" style="margin-top:14px">
      <div class="deliverable-card"><div class="deliverable-icon">◎</div><h3>Fiche décision</h3><p>Un visuel vertical avec verdict, finances, risques et prochaines actions.</p><button class="btn primary" id="downloadDecisionSvg">Télécharger SVG</button></div>
      <div class="deliverable-card"><div class="deliverable-icon">◫</div><h3>Matrice des risques</h3><p>Graphique 2D probabilité × gravité, avec les principaux risques du projet.</p><button class="btn" id="downloadRiskSvg">Télécharger SVG</button></div>
      <div class="deliverable-card"><div class="deliverable-icon">▦</div><h3>Plan fonctionnel</h3><p>Le plan interactif courant, exporté en SVG pour reprise ou impression.</p><button class="btn" id="downloadPlanSvg">Télécharger SVG</button></div>
      <div class="deliverable-card"><div class="deliverable-icon">90</div><h3>Feuille de route</h3><p>Les actions 30/60/90 jours restent exportables en CSV.</p><button class="btn" id="downloadRoadmapV8">Télécharger CSV</button></div>
      <div class="deliverable-card"><div class="deliverable-icon">PDF</div><h3>Dossier complet</h3><p>Le dossier maître, banque, mairie ou investisseur est prêt pour impression PDF.</p><button class="btn" id="printDossierV8">Ouvrir le dossier</button></div>
      <div class="deliverable-card"><div class="deliverable-icon">{ }</div><h3>Sauvegarde projet</h3><p>Exporte toutes les données pour sauvegarder ou transférer ton projet.</p><button class="btn ghost" id="exportProjectV8">Export JSON</button></div>
    </div>
    <div class="section-title"><h2>Aperçu fiche décision</h2><p>Version synthétique générée instantanément.</p></div><div id="decisionPreview" class="decision-preview"></div>
  </section>`)
}
function safeSvgText(s){return String(s??'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}
function wrapText(text,max=54){const words=String(text||'').split(/\s+/),lines=[];let line='';words.forEach(w=>{const n=(line+' '+w).trim();if(n.length>max&&line){lines.push(line);line=w}else line=n});if(line)lines.push(line);return lines.slice(0,4)}
function svgDownload(name,svg){const blob=new Blob([svg],{type:'image/svg+xml;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function decisionSvg(){const s=scoreProject(),f=calcFinance(),c=controls(),rs=risks().slice(0,4),actions=c.filter(x=>x.status!=='OK').slice(0,4),terr=state.territory?.live;const title=state.name||'Projet sans nom',loc=terr?.nom||state.location||'Territoire à définir';let y=70;
  const t=(x,yy,txt,size=26,weight=400,fill='#eaf3fb')=>`<text x="${x}" y="${yy}" font-family="Arial,sans-serif" font-size="${size}" font-weight="${weight}" fill="${fill}">${safeSvgText(txt)}</text>`;
  let body=`<rect width="1200" height="1600" fill="#071321"/><rect x="42" y="42" width="1116" height="1516" rx="34" fill="#0d1b2b" stroke="#31516d" stroke-width="2"/>${t(80,105,'JLG PROJECT LAB 360 · V8',22,700,'#d7af55')}${t(80,160,title,45,800)}${t(80,202,loc,24,400,'#9eb1c3')}`;y=275;
  body+=`<rect x="80" y="${y}" width="1040" height="150" rx="25" fill="#102a3b"/>${t(115,y+48,'DÉCISION',18,700,'#9eb1c3')}${t(115,y+103,s.verdict,42,900,s.verdict==='GO'?'#50d28c':s.verdict.includes('CONDITIONS')?'#f4c75e':'#ff7171')}${t(760,y+48,'CONFIANCE',18,700,'#9eb1c3')}${t(760,y+103,s.confidence+'/100',42,900)}`;y+=190;
  const kpis=[['CA / mois',fmt(f.revenue)],['Résultat / mois',fmt(f.profit)],['CAPEX',fmt(f.capex)],['Point mort',f.breakeven+' ventes']];kpis.forEach((k,i)=>{const x=80+(i%2)*520,yy=y+Math.floor(i/2)*130;body+=`<rect x="${x}" y="${yy}" width="490" height="108" rx="20" fill="#0a1725" stroke="#233b51"/>${t(x+25,yy+34,k[0],17,600,'#9eb1c3')}${t(x+25,yy+76,k[1],28,800)}`});y+=285;
  body+=t(80,y,'RISQUES PRIORITAIRES',20,800,'#d7af55');y+=35;rs.forEach(r=>{body+=`<rect x="80" y="${y}" width="1040" height="76" rx="16" fill="#101d2b"/>${t(105,y+32,r.name,18,700)}${t(105,y+57,r.mit,15,400,'#9eb1c3')}${t(1040,y+45,String(r.score),25,900,r.score>=35?'#ff7171':'#f4c75e')}`;y+=88});y+=20;
  body+=t(80,y,'PROCHAINES ACTIONS',20,800,'#d7af55');y+=38;actions.forEach((a,i)=>{const lines=wrapText(a.action,70);body+=t(90,y,`${i+1}. ${a.name}`,18,700);y+=26;lines.forEach(l=>{body+=t(115,y,l,15,400,'#9eb1c3');y+=21});y+=15});
  body+=t(80,1510,`Généré le ${new Date().toLocaleDateString('fr-FR')} · Hypothèses à confirmer par preuves et validations professionnelles.`,14,400,'#71879a');return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 1600">${body}</svg>`}
function riskMatrixSvg(){const rr=risks().slice(0,10);const W=1100,H=760,m=100,plotW=850,plotH=530,t=(x,y,s,size=18,fill='#eaf3fb')=>`<text x="${x}" y="${y}" font-family="Arial,sans-serif" font-size="${size}" fill="${fill}">${safeSvgText(s)}</text>`;let b=`<rect width="${W}" height="${H}" fill="#071321"/><rect x="35" y="35" width="1030" height="690" rx="26" fill="#0d1b2b" stroke="#31516d"/>${t(75,85,'MATRICE DES RISQUES · '+(state.name||'PROJET'),28,'#eaf3fb')}<line x1="${m}" y1="${H-m}" x2="${m+plotW}" y2="${H-m}" stroke="#8aa4b8"/><line x1="${m}" y1="${H-m}" x2="${m}" y2="${H-m-plotH}" stroke="#8aa4b8"/>${t(420,710,'PROBABILITÉ →',16,'#9eb1c3')}${t(35,380,'GRAVITÉ',16,'#9eb1c3')}`;[25,50,75,100].forEach(v=>{const x=m+plotW*v/100,y=H-m-plotH*v/100;b+=`<line x1="${x}" y1="${H-m}" x2="${x}" y2="${H-m-plotH}" stroke="#1f3345"/>${t(x-10,H-m+25,v,13,'#71879a')}<line x1="${m}" y1="${y}" x2="${m+plotW}" y2="${y}" stroke="#1f3345"/>${t(m-35,y+5,v,13,'#71879a')}`});rr.forEach((r,i)=>{const x=m+plotW*r.p/100,y=H-m-plotH*r.s/100,fill=r.score>=35?'#ff7171':r.score>=20?'#f4c75e':'#50d28c';b+=`<circle cx="${x}" cy="${y}" r="${12+Math.min(18,r.score/3)}" fill="${fill}" fill-opacity=".78" stroke="#fff" stroke-opacity=".5"/><text x="${x+18}" y="${y-12}" font-family="Arial,sans-serif" font-size="13" fill="#eaf3fb">${safeSvgText((i+1)+'. '+r.name)}</text>`});return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}">${b}</svg>`}
function exportPlanSvgV8(){showPage('visuals');setTimeout(()=>{const svg=$('#layoutSvg svg');if(!svg)return toast('Plan non disponible');let content=svg.outerHTML;if(!content.includes('xmlns='))content=content.replace('<svg','<svg xmlns="http://www.w3.org/2000/svg"');svgDownload((slug(state.name)||'projet')+'-plan-v8.svg',content);toast('Plan SVG téléchargé')},100)}
function renderDeliverablesV8(){const el=$('#deliverableSummary'),prev=$('#decisionPreview');if(!el||!prev)return;const s=scoreProject(),f=calcFinance();el.innerHTML=[['Décision',s.verdict],['Confiance',s.confidence+'/100'],['CAPEX',fmt(f.capex)],['Données live',state.territory?.live?'Oui':'Non']].map(([n,v])=>`<div class="kpi"><span>${esc(n)}</span><strong style="font-size:20px">${esc(v)}</strong></div>`).join('');prev.innerHTML=decisionSvg()}
function bindV8Deliverables(){
  $('#downloadDecisionSvg')&&($('#downloadDecisionSvg').onclick=()=>svgDownload((slug(state.name)||'projet')+'-fiche-decision-v8.svg',decisionSvg()));
  $('#downloadRiskSvg')&&($('#downloadRiskSvg').onclick=()=>svgDownload((slug(state.name)||'projet')+'-matrice-risques-v8.svg',riskMatrixSvg()));
  $('#downloadPlanSvg')&&($('#downloadPlanSvg').onclick=exportPlanSvgV8);$('#downloadRoadmapV8')&&($('#downloadRoadmapV8').onclick=exportRoadmap);$('#printDossierV8')&&($('#printDossierV8').onclick=()=>showPage('dossier'));$('#exportProjectV8')&&($('#exportProjectV8').onclick=exportJson)
}
const V8D_oldShowPage=showPage;showPage=function(id){V8D_oldShowPage(id);if(id==='deliverables')renderDeliverablesV8()};
const V8D_oldRenderAll=renderAll;renderAll=function(){V8D_oldRenderAll();renderDeliverablesV8()};
function initV8Deliverables(){injectV8Deliverables();bindV8Deliverables();renderDeliverablesV8();}
initV8Deliverables();
