/* JLG Project Lab 360 — V9 Premium official risk & urbanism intelligence */
const V9_VERSION='9.0.0';
function ensureV9State(){
  state.premium=state.premium||{};
  state.premium.risks=state.premium.risks||null;
  state.premium.catnat=state.premium.catnat||null;
  state.premium.urbanism=state.premium.urbanism||null;
  state.premium.updatedAt=state.premium.updatedAt||null;
  state.premium.sync=state.premium.sync||{endpoint:'',projectKey:'',lastSync:null};
  state.premium.audit=state.premium.audit||{};
}
function injectV9Shell(){
  document.title='JLG Project Lab 360 — V9 Premium';
  const vp=document.querySelector('.version-pill');if(vp)vp.textContent='V9';
  const bs=document.querySelector('.brand small');if(bs)bs.textContent='V9 Premium · risques, urbanisme & finition';
  if(!document.querySelector('link[href*="v9.css"]')){const l=document.createElement('link');l.rel='stylesheet';l.href='./v9.css?v=9.0.0';document.head.appendChild(l)}
  const tabs=$('#tabs');
  if(tabs&&!tabs.querySelector('[data-page="premium"]')){
    const territory=tabs.querySelector('[data-page="territory"]');
    (territory||tabs.lastElementChild)?.insertAdjacentHTML(territory?'afterend':'afterend','<button class="tab" data-page="premium">Premium</button>');
  }
  const territoryPage=$('#territory');
  if(territoryPage&&!$('#premium'))territoryPage.insertAdjacentHTML('afterend',`<section id="premium" class="page">
    <div class="section-title"><div><span class="section-kicker">V9 · PREMIUM</span><h2>Risques, urbanisme & conformité</h2></div><p>Données publiques officielles, datées, et limites d’usage clairement indiquées.</p></div>
    <div class="premium-hero card"><div><span class="eyebrow">AUDIT OFFICIEL</span><h2 id="premiumTitle">${esc(state.location||'Territoire à définir')}</h2><p>Complète l’intelligence territoriale avec Géorisques et le Géoportail de l’Urbanisme. Ces informations sont un contexte de décision, pas une validation juridique de la parcelle.</p></div><div class="row no-print"><button id="runPremiumResearch" class="btn primary">Lancer l’audit officiel</button><button id="clearPremiumResearch" class="btn ghost">Effacer</button></div></div>
    <div id="premiumStatus" class="callout" style="margin-top:12px">Audit officiel non lancé.</div>
    <div id="premiumKpis" class="grid g4" style="margin-top:14px"></div>
    <div class="premium-grid" style="margin-top:14px">
      <div class="card"><div class="card-head"><h3>Risques communaux</h3><span class="pill">Géorisques</span></div><div id="riskOfficialList"></div></div>
      <div class="card"><div class="card-head"><h3>Catastrophes naturelles</h3><span class="pill">CATNAT</span></div><div id="catnatList"></div></div>
      <div class="card"><div class="card-head"><h3>Document d’urbanisme</h3><span class="pill">IGN / GPU</span></div><div id="urbanDoc"></div></div>
      <div class="card"><div class="card-head"><h3>Zonage au point</h3><span class="pill">API Carto</span></div><div id="urbanZone"></div></div>
      <div class="card premium-wide"><div class="card-head"><h3>Impact sur le projet</h3><span class="pill">lecture Project Lab</span></div><div id="premiumImpact"></div></div>
      <div class="card premium-wide"><div class="card-head"><h3>Checklist de validation professionnelle</h3><span class="pill">avant GO</span></div><div id="professionalChecks"></div></div>
    </div>
    <div class="section-title"><div><span class="section-kicker">QUALITÉ FINALE</span><h2>Audit de complétude premium</h2></div><p>Dernière couche avant dossier final.</p></div>
    <div id="premiumAudit" class="premium-audit"></div>
  </section>`);
}
function premiumSource(label,url){return{label,url,date:new Date().toLocaleString('fr-FR'),iso:new Date().toISOString()}}
function georisquesBase(){return'https://www.georisques.gouv.fr/api/v1'}
function urbanPoint(){const c=state.territory?.live?.centre?.coordinates;return Array.isArray(c)&&c.length>=2?{type:'Point',coordinates:[Number(c[0]),Number(c[1])]}:null}
async function fetchJsonTimeout(url,opt={},ms=18000){const ctl=new AbortController(),to=setTimeout(()=>ctl.abort(),ms);try{const r=await fetch(url,{...opt,signal:ctl.signal});if(!r.ok)throw new Error(`${r.status} ${r.statusText||''}`.trim());return await r.json()}finally{clearTimeout(to)}}
async function fetchOfficialRisks(){const code=state.territory?.live?.code;if(!code)throw new Error('Lance d’abord Territoire live pour obtenir le code INSEE.');const url=`${georisquesBase()}/gaspar/risques?code_insee=${encodeURIComponent(code)}`;const j=await fetchJsonTimeout(url);let list=[];const data=Array.isArray(j?.data)?j.data:[];data.forEach(row=>{const det=Array.isArray(row?.risques_detail)?row.risques_detail:[];det.forEach(r=>list.push({label:r.libelle_risque_long||r.libelle_risque||r.num_risque||'Risque non libellé',code:r.num_risque||'',family:r.libelle_risque_jo||''}))});list=[...new Map(list.map(x=>[x.label,x])).values()];return{list,rawCount:Number(j?.results||list.length),source:premiumSource('Géorisques — risques communaux',url)}}
async function fetchOfficialCatnat(){const code=state.territory?.live?.code;if(!code)throw new Error('Code INSEE manquant.');const url=`${georisquesBase()}/gaspar/catnat?code_insee=${encodeURIComponent(code)}`;const j=await fetchJsonTimeout(url);const data=Array.isArray(j?.data)?j.data:[];const rows=[];data.forEach(group=>{if(Array.isArray(group?.catnat_detail))group.catnat_detail.forEach(x=>rows.push(x));else if(group&&typeof group==='object')rows.push(group)});const norm=rows.map(x=>({risk:x.libelle_risque_jo||x.libelle_risque_long||x.libelle_risque||'Catastrophe naturelle',start:x.date_debut_evt||x.date_debut||'',end:x.date_fin_evt||x.date_fin||'',order:x.date_arrete||'',publication:x.date_publication_arrete||x.date_publication||''}));return{list:norm,source:premiumSource('Géorisques — CATNAT',url)}}
async function fetchUrbanism(){const point=urbanPoint();if(!point)throw new Error('Coordonnées du territoire manquantes.');const geom=encodeURIComponent(JSON.stringify(point)),base='https://apicarto.ign.fr/api/gpu';const urls={document:`${base}/document?geom=${geom}`,zone:`${base}/zone-urba?geom=${geom}`,prescription:`${base}/prescription-surf?geom=${geom}`};const out={documents:[],zones:[],prescriptions:[],sources:[]};
  try{const j=await fetchJsonTimeout(urls.document);out.documents=(j?.features||[]).map(f=>f.properties||{});out.sources.push(premiumSource('API Carto IGN — document urbanisme',urls.document))}catch(e){out.documentError=e.message}
  try{const j=await fetchJsonTimeout(urls.zone);out.zones=(j?.features||[]).map(f=>f.properties||{});out.sources.push(premiumSource('API Carto IGN — zonage urbanisme',urls.zone))}catch(e){out.zoneError=e.message}
  try{const j=await fetchJsonTimeout(urls.prescription);out.prescriptions=(j?.features||[]).map(f=>f.properties||{}).slice(0,30);out.sources.push(premiumSource('API Carto IGN — prescriptions surfaciques',urls.prescription))}catch(e){out.prescriptionError=e.message}
  return out
}
async function runPremiumResearch(){ensureV9State();if(!state.territory?.live){toast('Commence par Territoire live');showPage('territory');return}const st=$('#premiumStatus');if(st)st.innerHTML='<b>Audit en cours…</b> Interrogation Géorisques et Géoportail de l’Urbanisme.';let risk=null,cat=null,urb=null,errors=[];try{risk=await fetchOfficialRisks()}catch(e){errors.push('Risques : '+e.message)}try{cat=await fetchOfficialCatnat()}catch(e){errors.push('CATNAT : '+e.message)}try{urb=await fetchUrbanism()}catch(e){errors.push('Urbanisme : '+e.message)}state.premium.risks=risk;state.premium.catnat=cat;state.premium.urbanism=urb;state.premium.updatedAt=new Date().toISOString();addPremiumEvidence();save(false);renderPremium();renderAll();if(st)st.innerHTML=`<b>Audit terminé.</b> ${errors.length?esc(errors.join(' · ')):'Toutes les sources principales ont répondu.'}`;toast('Audit premium terminé')}
function clearPremiumResearch(){ensureV9State();state.premium.risks=null;state.premium.catnat=null;state.premium.urbanism=null;state.premium.updatedAt=null;save(false);renderPremium();toast('Données premium effacées')}
function addPremiumEvidence(){const c=state.territory?.live;if(!c)return;const today=new Date().toLocaleDateString('fr-FR');if(state.premium.risks){const label=`Géorisques commune — ${c.nom}`;if(!state.evidence.some(e=>e.label===label))state.evidence.push({label,detail:`${state.premium.risks.list.length} risque(s) communal(aux) récupéré(s) via Géorisques v1 le ${today}. Contexte communal : validation adresse/parcelle nécessaire.`,date:today})}if(state.premium.urbanism){const label=`Urbanisme GPU — ${c.nom}`;if(!state.evidence.some(e=>e.label===label))state.evidence.push({label,detail:`Document/zonage interrogés au centre de la commune via API Carto IGN le ${today}. À vérifier sur l’adresse ou la parcelle exacte du projet.`,date:today})}}
function riskKeywords(){const txt=(state.premium.risks?.list||[]).map(x=>x.label.toLowerCase()).join(' ');return{flood:/inond|crue|submersion/.test(txt),fire:/feu|incendie de forêt/.test(txt),movement:/mouvement|terrain|argile|retrait/.test(txt),seismic:/séism|sism/.test(txt),industrial:/industri|technolog|canalis|pollution/.test(txt),radon:/radon/.test(txt)}}
function premiumProjectImpact(){const out=[],k=riskKeywords(),p=state.premium.urbanism||{},zones=p.zones||[],docs=p.documents||[];if(k.flood)out.push(['bad','Risque inondation/crue recensé au niveau communal','Pour un site extérieur, bord de lac/rivière ou activité accueillant du public, vérifier impérativement la parcelle, le PPRI/PPR et le plan de repli.']);if(k.fire)out.push(['warn','Risque incendie/feu de forêt recensé','Vérifier débroussaillement, accès secours, matériaux et restrictions saisonnières selon le site.']);if(k.movement)out.push(['warn','Risque sol/mouvement de terrain recensé','Pour travaux, bâtiment ou aménagement lourd, une validation géotechnique peut devenir déterminante.']);if(k.industrial)out.push(['warn','Risque technologique ou pollution recensé','Vérifier la proximité réelle, les servitudes, SIS/ICPE et les usages compatibles.']);if(docs.length)out.push(['good','Document d’urbanisme détecté',`Le point interrogé est couvert par ${docs[0].du_type||docs[0].type||'un document'} (${docs[0].name||docs[0].partition||'référence disponible'}).`]);else out.push(['warn','Aucun document d’urbanisme détecté au point de référence','Cela ne signifie pas absence de règles : vérifier GPU, mairie et éventuel RNU/carte communale.']);if(zones.length){const z=zones[0],name=z.libelle||z.libelle_zone||z.typezone||z.type_zone||z.zone||'zone détectée';out.push(['good','Zonage détecté au point de référence',`${name}. Ce zonage doit être confirmé sur l’adresse/parcelle exacte avant décision.`])}if(!out.length)out.push(['warn','Données officielles encore insuffisantes','Aucune conclusion de conformité ne doit être tirée sans adresse/parcelle et vérification auprès des interlocuteurs compétents.']);return out}
function professionalChecklist(){const a=[['Adresse/parcelle exacte du projet','À confirmer','L’analyse actuelle travaille au niveau commune/point central tant que la parcelle n’est pas fournie.'],['Règlement écrit du PLU/PLUi ou document applicable','À lire','Un code de zone ne suffit pas : il faut lire les règles d’usage, implantation, stationnement, aspect et équipements.'],['Servitudes d’utilité publique','À vérifier','Monuments historiques, réseaux, risques, environnement ou autres SUP peuvent changer la faisabilité.'],['ERP / sécurité incendie / accessibilité','Selon activité','À confirmer avec mairie, SDIS/bureau de contrôle/technicien selon le projet.'],['Assurance et responsabilités','Obligatoire avant GO','Faire confirmer par écrit la couverture de l’activité et du site.']];if(['lake','river','square','publicsite'].includes(state.site)||state.ownership==='public')a.push(['Occupation du domaine/site','Écrit obligatoire','Convention/AOT/accord avec durée, conditions, révocabilité, redevance et remise en état.']);if(state.type==='food')a.push(['Hygiène / boissons / déchets','Selon offre réelle','Valider eau, froid, stockage, nettoyage, déchets et licences éventuelles.']);return a}
function premiumAuditItems(){const territory=!!state.territory?.live,premium=!!state.premium.updatedAt,docs=documentTemplates?documentTemplates():[],perm=permitTemplates?permitTemplates():[],hy=hypothesisTemplates?hypothesisTemplates():[],f=calcFinance(),c=controls(),items=[
['Territoire officiel chargé',territory,'Lancer Territoire live.'],['Risques officiels interrogés',!!state.premium.risks,'Lancer l’audit premium.'],['Urbanisme interrogé',!!state.premium.urbanism,'Lancer l’audit premium.'],['Au moins 2 devis',state.execution?.quotes?.length>=2,'Ajouter des devis réels.'],['Autorisations critiques sécurisées',perm.filter(x=>x.priority==='critical').every(x=>['done','na'].includes(state.execution?.permits?.[x.id]||'todo')),'Traiter les autorisations critiques dans Montage V7.'],['Hypothèses clés testées',hy.filter(x=>x.priority==='critical').every(x=>(state.execution?.hypotheses?.[x.id]||'unknown')==='validated'),'Valider la demande, le prix, le volume, la marge et l’exploitation.'],['Documents critiques obtenus',docs.filter(x=>x.priority==='critical').every(x=>['obtained','na'].includes(state.workflow?.documents?.[x.id]||'missing')),'Compléter le registre Documents.'],['Scénario prudent non déficitaire',calcFinance({price:.95,qty:.7,margin:.92,opex:1.08}).profit>=0,'Revoir le modèle économique ou le périmètre.'],['Financement bouclé',f.remaining<=Math.max(1000,f.capex*.1),'Boucler le reste à financer.'],['Aucun bloquant Tour de contrôle',c.filter(x=>x.status==='BLOQUANT').length===0,'Lever les bloquants internes.'],['Dossier décisionnel généré',!!state.analysis,'Construire le dossier 360°.'],['Preuves externes ≥ 4',(state.evidence||[]).length>=4,'Ajouter devis, accords, données terrain et validations.']];return items}
function premiumCompletion(){const it=premiumAuditItems();return Math.round(it.filter(x=>x[1]).length/it.length*100)}
function renderPremium(){ensureV9State();const title=$('#premiumTitle');if(title)title.textContent=state.territory?.live?.nom||state.location||'Territoire à définir';const risk=state.premium.risks,cat=state.premium.catnat,urb=state.premium.urbanism,updated=state.premium.updatedAt;const rk=(risk?.list||[]).length,catn=(cat?.list||[]).length,docs=(urb?.documents||[]).length,zones=(urb?.zones||[]).length;const kpis=$('#premiumKpis');if(kpis)kpis.innerHTML=[['Risques recensés',rk],['CATNAT',catn],['Documents GPU',docs],['Zonages',zones]].map(([n,v])=>`<div class="kpi"><span>${esc(n)}</span><strong>${esc(v)}</strong></div>`).join('');const st=$('#premiumStatus');if(st&&!st.textContent.includes('cours'))st.innerHTML=updated?`<b>Données récupérées le ${new Date(updated).toLocaleString('fr-FR')}.</b> Contexte communal/point central : à confirmer sur adresse ou parcelle.`:'Audit officiel non lancé.';
  const rl=$('#riskOfficialList');if(rl)rl.innerHTML=risk?(risk.list.length?risk.list.map(x=>`<div class="premium-row"><b>${esc(x.label)}</b><span class="pill">${esc(x.code||'commune')}</span></div>`).join(''):'<div class="callout">Aucun risque renvoyé par cet endpoint pour la commune. Ne pas interpréter comme absence totale de risque.</div>'):'<p class="muted">Lance l’audit officiel.</p>';
  const cl=$('#catnatList');if(cl)cl.innerHTML=cat?(cat.list.length?cat.list.slice(0,15).map(x=>`<div class="premium-row"><div><b>${esc(x.risk)}</b><small>${esc(x.start||'date n.c.')}${x.order?' · arrêté '+esc(x.order):''}</small></div></div>`).join(''):'<div class="callout">Aucun enregistrement CATNAT renvoyé.</div>'):'<p class="muted">Lance l’audit officiel.</p>';
  const ud=$('#urbanDoc');if(ud)ud.innerHTML=urb?(urb.documents?.length?urb.documents.slice(0,6).map(x=>`<div class="premium-row"><div><b>${esc(x.du_type||x.type||'Document')}</b><small>${esc(x.name||x.partition||x.grid_title||'référence non libellée')}</small></div><span class="pill">${esc(x.gpu_status||'GPU')}</span></div>`).join(''):`<div class="callout warn">${esc(urb.documentError||'Aucun document renvoyé au point interrogé.')}</div>`):'<p class="muted">Lance l’audit officiel.</p>';
  const uz=$('#urbanZone');if(uz)uz.innerHTML=urb?(urb.zones?.length?urb.zones.slice(0,8).map(x=>`<div class="premium-row"><div><b>${esc(x.libelle||x.libelle_zone||x.typezone||x.type_zone||x.zone||'Zone')}</b><small>${esc(x.destdomi||x.destination||x.partition||'')}</small></div></div>`).join(''):`<div class="callout warn">${esc(urb.zoneError||'Aucun zonage renvoyé au point interrogé.')}</div>`):'<p class="muted">Lance l’audit officiel.</p>';
  const imp=$('#premiumImpact');if(imp)imp.innerHTML=premiumProjectImpact().map(([cls,t,p])=>`<div class="impact-row ${cls}"><b>${esc(t)}</b><p>${esc(p)}</p></div>`).join('');const pc=$('#professionalChecks');if(pc)pc.innerHTML=professionalChecklist().map(([n,s,d])=>`<div class="check-pro"><div><b>${esc(n)}</b><small>${esc(d)}</small></div><span class="status ${s.includes('Oblig')?'block':'alert'}">${esc(s)}</span></div>`).join('');renderPremiumAudit()}
function renderPremiumAudit(){const el=$('#premiumAudit');if(!el)return;const items=premiumAuditItems(),pct=premiumCompletion(),ok=items.filter(x=>x[1]).length;el.innerHTML=`<div class="premium-score"><div><span class="eyebrow">COMPLÉTUDE PREMIUM</span><strong>${pct}%</strong><p>${ok}/${items.length} critères finalisés</p></div><div class="scorebar"><i style="width:${pct}%"></i></div></div><div class="audit-grid">${items.map(([n,done,a])=>`<div class="audit-item ${done?'done':''}"><span>${done?'✓':'!'}</span><div><b>${esc(n)}</b><small>${done?'Validé dans le dossier actuel.':esc(a)}</small></div></div>`).join('')}</div>`}
const V9_oldShowPage=showPage;showPage=function(id){V9_oldShowPage(id);if(id==='premium')renderPremium()};
const V9_oldRenderAll=renderAll;renderAll=function(){ensureV9State();V9_oldRenderAll();renderPremium()};
function bindV9(){const run=$('#runPremiumResearch');if(run)run.onclick=runPremiumResearch;const clear=$('#clearPremiumResearch');if(clear)clear.onclick=clearPremiumResearch}
function initV9(){ensureV9State();injectV9Shell();bindV9();renderPremium();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js?v=9.0.0').then(r=>r.update()).catch(()=>{})}
initV9();
